name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-04-01
        default: true
        override: true
        components: rust-src, llvm-tools-preview
        target:  riscv64gc-unknown-none-elf
    
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    
    - name: Build
      run: cargo build --verbose
